# Generated by Django 5.1.1 on 2024-09-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient')], default='Patient', max_length=20)),
                ('specialization', models.CharField(blank=True, choices=[('allergy_immunology', 'Allergy and Immunology'), ('anesthesiology', 'Anesthesiology'), ('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('endocrinology', 'Endocrinology'), ('gastroenterology', 'Gastroenterology'), ('geriatrics', 'Geriatrics'), ('hematology', 'Hematology'), ('infectious_disease', 'Infectious Disease'), ('internal_medicine', 'Internal Medicine'), ('nephrology', 'Nephrology'), ('neurology', 'Neurology'), ('obstetrics_gynecology', 'Obstetrics and Gynecology (OB/GYN)'), ('oncology', 'Oncology'), ('ophthalmology', 'Ophthalmology'), ('orthopedic_surgery', 'Orthopedic Surgery'), ('otolaryngology', 'Otolaryngology (ENT)'), ('pediatrics', 'Pediatrics'), ('physical_medicine_rehabilitation', 'Physical Medicine and Rehabilitation'), ('psychiatry', 'Psychiatry'), ('pulmonology', 'Pulmonology'), ('rheumatology', 'Rheumatology'), ('surgery', 'Surgery'), ('urology', 'Urology'), ('emergency_medicine', 'Emergency Medicine'), ('addiction_medicine', 'Addiction Medicine'), ('critical_care_medicine', 'Critical Care Medicine')], default='', max_length=50, null=True)),
                ('experience_years', models.IntegerField(default=0)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient')], default='Patient', max_length=20)),
                ('medical_history', models.TextField(default='')),
                ('age', models.IntegerField(default=0)),
                ('height', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('weight', models.IntegerField(default=0)),
                ('gender', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male')], max_length=20)),
                ('bloodgroup', models.CharField(default='', max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
