# Generated by Django 5.1.1 on 2024-09-12 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20240912_1226'),
    ]

    operations = [
    ]
