# Generated by Django 5.1.1 on 2024-09-12 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_doctor_patient_delete_user'),
    ]

    operations = [
    ]
