# Generated by Django 5.1.1 on 2024-09-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_doctor_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='bloodgroup',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bloodgroup_type',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
