# Generated by Django 5.1.1 on 2024-09-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_doctor_password_doctor_location_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient')], default='Patient', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient')], default='Patient', max_length=20),
        ),
    ]
