# Generated by Django 5.1.1 on 2024-09-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_doctor_role_alter_patient_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
