# Generated by Django 5.1.1 on 2024-09-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_doctor_experience_years_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
