# Generated by Django 5.1.1 on 2024-09-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_doctor_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(blank=True, choices=[('allergy_immunology', 'Allergy and Immunology'), ('anesthesiology', 'Anesthesiology'), ('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('endocrinology', 'Endocrinology'), ('gastroenterology', 'Gastroenterology'), ('geriatrics', 'Geriatrics'), ('hematology', 'Hematology'), ('infectious_disease', 'Infectious Disease'), ('internal_medicine', 'Internal Medicine'), ('nephrology', 'Nephrology'), ('neurology', 'Neurology'), ('obstetrics_gynecology', 'Obstetrics and Gynecology (OB/GYN)'), ('oncology', 'Oncology'), ('ophthalmology', 'Ophthalmology'), ('orthopedic_surgery', 'Orthopedic Surgery'), ('otolaryngology', 'Otolaryngology (ENT)'), ('pediatrics', 'Pediatrics'), ('physical_medicine_rehabilitation', 'Physical Medicine and Rehabilitation'), ('psychiatry', 'Psychiatry'), ('pulmonology', 'Pulmonology'), ('rheumatology', 'Rheumatology'), ('surgery', 'Surgery'), ('urology', 'Urology'), ('emergency_medicine', 'Emergency Medicine'), ('addiction_medicine', 'Addiction Medicine'), ('critical_care_medicine', 'Critical Care Medicine')], default='', max_length=50, null=True),
        ),
    ]
